[dev]
  command = "npm run functions"
  publish = "public"
  functions = "functions"

[build]
  command = "npm run functions"
  publish = "public"
  functions = "functions"

[template.environment]
  STRIPE_PUBLISHABLE_KEY = "pk_test_YVo4zHtsiia3uV3ds7Us0iM400ZbnZRVTJ"
  STRIPE_SECRET_KEY = "sk_test_g3nWTRi8tw0D1mUxEAOvCoxu00XFsRbccq"
  STRIPE_WEBHOOK_SECRET = "[Optional] Add your webhook secret here: whsec_xxx"
